# Generated by Django 3.0.5 on 2020-04-27 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='active',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='regdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
