# Generated by Django 3.0.5 on 2020-04-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0003_auto_20200427_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
