# Generated by Django 3.0.5 on 2020-04-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0004_user_custom_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boards',
            name='regdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
