# Generated by Django 3.0.5 on 2020-04-29 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0005_auto_20200428_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipts',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
