# Generated by Django 3.0.5 on 2020-04-29 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0006_receipts_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boards',
            name='entry',
            field=models.ManyToManyField(blank=True, null=True, related_name='boards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='boards',
            name='register',
            field=models.ForeignKey(blank=True, db_column='register', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='board_register', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='receipts',
            name='register',
            field=models.ForeignKey(blank=True, db_column='register', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
