# Generated by Django 3.0.5 on 2020-04-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0007_auto_20200429_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boards',
            name='regdate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
