# Generated by Django 3.0.5 on 2020-04-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0008_auto_20200429_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='regdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='receipts',
            name='regdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='regdate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
