# Generated by Django 3.0.5 on 2020-04-29 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0009_auto_20200429_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gateway.Receipts'),
        ),
        migrations.AlterField(
            model_name='receipts',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gateway.Boards'),
        ),
    ]
