# Generated by Django 3.0.5 on 2020-04-30 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0010_auto_20200429_1702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boards',
            options={'ordering': ('-board_id',)},
        ),
        migrations.AlterField(
            model_name='boards',
            name='register',
            field=models.ForeignKey(blank=True, db_column='register', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='board_register', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='receipts',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gateway.Boards'),
        ),
        migrations.AlterField(
            model_name='receipts',
            name='register',
            field=models.ForeignKey(blank=True, db_column='register', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
